#!/bin/bash
str1="HDMI-1"
str2="$(xrandr --query | grep HD | awk {'print $1'})"

if [ "$str1" = "$str2" ]; then

  xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate normal && nitrogen --restore
else
  echo "monitor not connected"
fi
